// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDukAnkfiUyE6e9vmxKli0oXkQxpGc2ExQ',
    appId: '1:149157542551:web:4c43d67eedc61da3e5c7d2',
    messagingSenderId: '149157542551',
    projectId: 'chatbox-app-35ae2',
    authDomain: 'chatbox-app-35ae2.firebaseapp.com',
    storageBucket: 'chatbox-app-35ae2.appspot.com',
    measurementId: 'G-W3B5PCDF5G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkbYwgFKydw6pQ5R9JIxfPBzg78MpXUao',
    appId: '1:149157542551:android:ad4c29acd777162ae5c7d2',
    messagingSenderId: '149157542551',
    projectId: 'chatbox-app-35ae2',
    storageBucket: 'chatbox-app-35ae2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQo-zydrROc9RiXl3STStu3rp7zEEje7M',
    appId: '1:149157542551:ios:8ee36fe322dbe4a4e5c7d2',
    messagingSenderId: '149157542551',
    projectId: 'chatbox-app-35ae2',
    storageBucket: 'chatbox-app-35ae2.appspot.com',
    iosBundleId: 'com.example.chatboxApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQo-zydrROc9RiXl3STStu3rp7zEEje7M',
    appId: '1:149157542551:ios:52075e48cb904ed9e5c7d2',
    messagingSenderId: '149157542551',
    projectId: 'chatbox-app-35ae2',
    storageBucket: 'chatbox-app-35ae2.appspot.com',
    iosBundleId: 'com.example.chatboxApp.RunnerTests',
  );
}
